### ISSUE TITLE
Create Github Pages

### ISSUE THREAD

**Issue by clergetm** [clergetm/Jandas#5]
# TODO
- [x] Create simple Github Page
- [x] Add jacoco report
- [x] Add javadoc

## MAYBE
- [x] Create a README
- [x] Convert README into HTML

**Comment by clergetm** [comment]
Done with #9
